config/routes.rb
Rails.application.routes.draw do
  resources :transactions, only: [:index, :create] do 
    collection do 
      get :credits
      get :withdraws
      get :withdrawals
      post :withdraw
      get :deposits
      get :deposit
      post :topup
      get :debits
      get :users
      get :teams
      get :stocks
    end
  end
  
  devise_for :teams, path: 'teams'
  devise_for :stocks, path: 'stocks'
  devise_for :users, path: 'users'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, path: 'admins'
  root 'transactions#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/wallet.rb
module Wallet
  extend ActiveSupport::Concern

  included do
    after_create :init_default_balance
    has_many :credits, -> { where.not(targetable: nil) }, class_name: 'Transaction', as: :sourceable
    has_many :withdraws, -> { where(targetable: nil) }, class_name: 'Transaction', as: :sourceable
    has_many :debits, -> { where.not(sourceable: nil) }, class_name: 'Transaction', as: :targetable
    has_many :deposits, -> { where(sourceable: nil) }, class_name: 'Transaction', as: :targetable
  end

  def transfer(target, amount)
    ActiveRecord::Base.transaction do
      credits.create(targetable: target, amount: amount)  
    end
  end

  def withdraw(amount)
    ActiveRecord::Base.transaction do
      credits.create(amount: amount)
    end
  end

  def deposit(amount)
    ActiveRecord::Base.transaction do
      deposits.create(amount: amount)
    end
  end

  def balance
    (sum_of_debits + sum_of_deposits) - (sum_of_credits + sum_of_withdraws)
  end

  def sum_of_debits
    debits.sum(:amount)
  end

  def sum_of_credits
    credits.sum(:amount)
  end

  def sum_of_withdraws
    withdraws.sum(:amount)
  end

  def sum_of_deposits
    deposits.sum(:amount)
  end

  def transactions_count
    debits.count + withdraws.count + credits.count + deposits.count
  end

  private
  def init_default_balance
    ActiveRecord::Base.transaction do
      #let's assume whenever user create new account, the admin will gave them 1000 balance for free
      debit = debits.new(sourceable: Admin.first, amount: 1000)
      debit.save(validate: false)
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  include Wallet
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/team.rb
class Team < ApplicationRecord
  include Wallet
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :sourceable, polymorphic: true, optional: true 
  belongs_to :targetable, polymorphic: true, optional: true 

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validate :check_current_balance, :check_self_transfer, on: :create

  private
  def check_current_balance
    errors.add(:amount, 'is not enough to process this transcation') if sourceable.present? && sourceable.balance - amount < 0
  end

  def check_self_transfer
    errors.add(:targetable, 'cannot same as transfer source') if sourceable.eql?(targetable)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Wallet
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user, :authenticate_logged_user!
  
  def set_user
    @current_logged_user = current_user || current_stock || current_team || current_admin
  end

  private 

  def check_role
    raise ActionController::RoutingError.new('Not Found') if @current_logged_user.class.to_s.eql?("Admin")
  end

  def authenticate_logged_user!
    class_name = @current_logged_user  ? @current_logged_user.class.to_s.downcase : 'user'
    eval("authenticate_#{class_name}!")
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :check_role
  def credits
    @credits = @current_logged_user.credits    
  end

  def debits
    @debits = @current_logged_user.debits    
  end

  def index
  end

  def users
    @transaction = @current_logged_user.credits.new
  end

  def teams
    @transaction = @current_logged_user.credits.new
  end

  def stocks
    @transaction = @current_logged_user.credits.new
  end
  
  def withdraws
    @withdraws = @current_logged_user.withdraws    
  end

  def withdrawals
    @transaction = @current_logged_user.withdraws.new
  end

  def withdraw
    @transaction = @current_logged_user.withdraw(transaction_params[:amount])
    if @transaction.save
      redirect_to withdraws_transactions_path
    else
      render "withdrawals"
    end
  end

  def deposits
    @deposits = @current_logged_user.deposits    
  end

  def deposit
    @transaction = @current_logged_user.deposits.new
  end

  def topup
    @transaction = @current_logged_user.deposit(transaction_params[:amount])
    if @transaction.save
      redirect_to deposits_transactions_path
    else
      render "deposit"
    end
  end

  def withdraw
    @transaction = @current_logged_user.withdraw(transaction_params[:amount])
    if @transaction.save
      redirect_to withdraws_transactions_path
    else
      render "withdrawals"
    end
  end
  

  def create
    @transaction = @current_logged_user.transfer(targetable(transaction_params[:targetable_type], transaction_params[:targetable_id]), transaction_params[:amount])
    if @transaction.save
      redirect_to credits_transactions_path
    else
      render "#{transaction_params[:targetable_type].to_s.downcase}s"
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:targetable_id, :amount, :targetable_type)
  end

  def targetable(targetable_type, id)
    eval("#{targetable_type}.find(#{id})")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_to_currency_id(number)
    number_to_currency(number, :unit => "Rp ", :separator => ",", :delimiter => ".")
  end

  def any_user_signed_in?
    user_signed_in? || stock_signed_in? || team_signed_in?
  end
end

app/helpers/transcations_helper.rb
module TranscationsHelper
  def user_options(current_logged_user)
    if current_logged_user.class.to_s.eql?('User')
      User.where.not(id: current_logged_user.id).pluck(:email, :id)
    else
      User.all.pluck(:email, :id)
    end
  end

  def team_options(current_logged_user)
    if current_logged_user.class.to_s.eql?('Team')
      Team.where.not(id: current_logged_user.id).pluck(:email, :id)
    else
      Team.all.pluck(:email, :id)
    end
  end

  def stock_options(current_logged_user)
    if current_logged_user.class.to_s.eql?('Stock')
      Stock.where.not(id: current_logged_user.id).pluck(:email, :id)
    else
      Stock.all.pluck(:email, :id)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "Mallet" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Mallet", root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if @current_logged_user.present? %>
              <li><%= link_to "Deposits Transactions", deposits_transactions_path %></li>
              <li><%= link_to "Debit Transacttraions", debits_transactions_path %></li>
              <li><%= link_to "Withdraw Transactions", withdraws_transactions_path %></li>
              <li><%= link_to "Credits Transactions", credits_transactions_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <% if any_user_signed_in? %>              
          <div class="col-md-3">
            <div class="well sidebar-nav">
              <b>Welcome <%= @current_logged_user.class %> - <%= @current_logged_user.email %></b>
              <ul class="nav nav-list">
                  <li class="nav-header">Transfer Menu</li>
                  <li><%= link_to "Deposit Money", deposit_transactions_path  %></li>
                  <li><%= link_to "Withdraw Money", withdrawals_transactions_path  %></li>
                  <li><%= link_to "Transfer To Users", users_transactions_path  %></li>
                  <li><%= link_to "Transfer To Stocks", stocks_transactions_path  %></li>
                  <li><%= link_to "Transfer To Teams", teams_transactions_path  %></li>
                  <li><%= button_to('Logout', eval("destroy_#{@current_logged_user.class.to_s.downcase}_session_path"), method: :delete) %></li>        
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        <% else %>
          <div class="col-md-3">
            <div class="well sidebar-nav">
              <h3>Select Users</h3>
              <ul class="nav nav-list">
                <%# <li class="nav-header">Sidebar</li> %>
                  <li><%= link_to "Login as Users", new_user_session_path  %></li>
                  <li><%= link_to "Login as Stocks", new_stock_session_path  %></li>
                  <li><%= link_to "Login as Teams", new_team_session_path  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->        
        <% end %>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/transactions/credits.html.erb
<table class="table table-striped">
  <tr>
    <th colspan = 5>
      <center>Credits Transactions</center>
    </th>
  <tr>
  <tr>
    <th>No</th>
    <th>Transcation Id</th>
    <th>Amount</th>
    <th>Transfered To</th>
    <th>Received at</th>
  </tr>
  <% @credits.each_with_index do |credit, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= credit.id %></td>
      <td><%= number_to_currency_id(credit.amount) %></td>
      <td><%= "#{credit.targetable.id} / #{credit.targetable.class} / #{credit.targetable.email}" %> / <%=  %></td>
      <td><%= credit.created_at %></td>
    </tr>    
  <% end %>
  <tr>
    <th colspan='2'>
      Total credits
    </th>
    <td>
      <%= number_to_currency_id @current_logged_user.sum_of_credits %>
    </td>
  <tr>
  <tr>
    <th colspan='2'>
      credits count
    </th>
    <td>
      <%= @current_logged_user.credits.count %>
    </td>
  <tr>  
</table>

app/views/transactions/debits.html.erb
<table class="table table-striped">
  <tr>
    <th colspan = 5>
      <center>Debits Transactions</center>
    </th>
  <tr>
  <tr>
    <th>No</th>
    <th>Transcation Id</th>
    <th>Amount</th>
    <th>Funds Source</th>
    <th>Received at</th>
  </tr>
  <% @debits.each_with_index do |debit, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= debit.id %></td>
      <td><%= number_to_currency_id(debit.amount) %></td>
      <td><%= "#{debit.sourceable.id} / #{debit.sourceable.class} / #{debit.sourceable.email}" %> / <%=  %></td>
      <td><%= debit.created_at %></td>
    </tr>    
  <% end %>
  <tr>
    <th colspan='2'>
      Total Debits
    </th>
    <td>
      <%= number_to_currency_id @current_logged_user.sum_of_debits %>
    </td>
  <tr>
  <tr>
    <th colspan='2'>
      Debits count
    </th>
    <td>
      <%= @current_logged_user.debits.count %>
    </td>
  <tr>  
</table>

app/views/transactions/deposit.html.erb
<% if @transaction.errors.any? %>
<ul>
  <% @transaction.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @transaction, url: 'topup' do |f| %>
  <div class="form-group">
    <%= f.label :amount %>
    <input type="hidden" 
       value="<%= form_authenticity_token() %>" 
       name="authenticity_token"/>
    <%= f.number_field :amount, min: 1, class: 'form-control', required: true %>
  </div>
  <%= f.submit "Transfer", class: 'btn btn-success' %>
<% end %>

app/views/transactions/deposits.html.erb
<table class="table table-striped">
  <tr>
    <th colspan = 5>
      <center>Deposits Transactions</center>
    </th>
  <tr>
  <tr>
    <th>No</th>
    <th>Transcation Id</th>
    <th>Amount</th>
    <th>Received at</th>
  </tr>
  <% @deposits.each_with_index do |deposit, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= deposit.id %></td>
      <td><%= number_to_currency_id(deposit.amount) %></td>
      <td><%= deposit.created_at %></td>
    </tr>    
  <% end %>
  <tr>
    <th colspan='2'>
      Total deposits
    </th>
    <td>
      <%= number_to_currency_id @current_logged_user.sum_of_deposits %>
    </td>
  <tr>
  <tr>
    <th colspan='2'>
      deposits count
    </th>
    <td>
      <%= @current_logged_user.deposits.count %>
    </td>
  <tr>  
</table>

app/views/transactions/index.html.erb
<p>*Balance is sum of deposit and debits minus sum of credits and withdrawals </p>
<table border="1" class="table table-striped">
  <tr>
    <th>Current Balance</th>
    <th>Total Deposits</th>
    <th>Total Debits</th>
    <th>Total withdrawals</th>
    <th>Total Credits</th>
  </tr>  
    <td><%= number_to_currency_id @current_logged_user.balance %></td>
    <td><%= number_to_currency_id @current_logged_user.sum_of_deposits %></td>
    <td><%= number_to_currency_id @current_logged_user.sum_of_debits %></td>
    <td><%= number_to_currency_id @current_logged_user.sum_of_withdraws %></td>
    <td><%= number_to_currency_id @current_logged_user.sum_of_credits %></td>
  <tr>
  </tr>
  <tr>
    <th>Transactions Count</th>
    <th>Deposits Count</th>
    <th>Debits Count</th>
    <th>withdrawals Count</th>
    <th>Credits Count</th>
  </tr>
  <tr>
    <td><%= @current_logged_user.transactions_count %></td>
    <td><%= @current_logged_user.deposits.count %></td>
    <td><%= @current_logged_user.debits.count %></td>
    <td><%= @current_logged_user.withdraws.count %></td>
    <td><%= @current_logged_user.credits.count %></td>
  </tr>
</table>

app/views/transactions/stocks.html.erb
<% if @transaction.errors.any? %>
<ul>
  <% @transaction.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @transaction do |f| %>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, min: 1, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label 'Transfer To' %>
    <%= f.select :targetable_id, options_for_select(stock_options(@current_logged_user)), {:prompt => "--select recipient--"}, {class: 'form-control', required: true } %>
    <%= f.hidden_field :targetable_type, value: "Stock" %>
  </div>
  <%= f.submit "Transfer", class: 'btn btn-success' %>
<% end %>

app/views/transactions/teams.html.erb
<% if @transaction.errors.any? %>
<ul>
  <% @transaction.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @transaction do |f| %>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, min: 1, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label 'Transfer To' %>
    <%= f.select :targetable_id, options_for_select(team_options(@current_logged_user)), {:prompt => "--select recipient--"}, {class: 'form-control', required: true } %>
    <%= f.hidden_field :targetable_type, value: "Team" %>
  </div>
  <%= f.submit "Transfer", class: 'btn btn-success' %>
<% end %>

app/views/transactions/users.html.erb
<% if @transaction.errors.any? %>
<ul>
  <% @transaction.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @transaction do |f| %>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, min: 1, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label 'Transfer To' %>
    <%= f.select :targetable_id, options_for_select(user_options(@current_logged_user)), {:prompt => "--select recipient--"}, {class: 'form-control', required: true } %>
    <%= f.hidden_field :targetable_type, value: "User" %>
  </div>
  <%= f.submit "Transfer", class: 'btn btn-success' %>
<% end %>

app/views/transactions/withdrawals.html.erb
<% if @transaction.errors.any? %>
<ul>
  <% @transaction.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @transaction, url: 'withdraw' do |f| %>
  <div class="form-group">
    <%= f.label :amount %>
    <input type="hidden" 
       value="<%= form_authenticity_token() %>" 
       name="authenticity_token"/>
    <%= f.number_field :amount, min: 1, class: 'form-control', required: true %>
  </div>
  <%= f.submit "Transfer", class: 'btn btn-success' %>
<% end %>

app/views/transactions/withdraws.html.erb
<table class="table table-striped">
  <tr>
    <th colspan = 5>
      <center>Withdraws Transactions</center>
    </th>
  <tr>
  <tr>
    <th>No</th>
    <th>Transcation Id</th>
    <th>Amount</th>
    <th>Received at</th>
  </tr>
  <% @withdraws.each_with_index do |withdraw, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= withdraw.id %></td>
      <td><%= number_to_currency_id(withdraw.amount) %></td>
      <td><%= withdraw.created_at %></td>
    </tr>    
  <% end %>
  <tr>
    <th colspan='2'>
      Total withdraws
    </th>
    <td>
      <%= number_to_currency_id @current_logged_user.sum_of_withdraws %>
    </td>
  <tr>
  <tr>
    <th colspan='2'>
      withdraws count
    </th>
    <td>
      <%= @current_logged_user.withdraws.count %>
    </td>
  <tr>  
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>